# Site settings
title: Bertland Hope
tagline: Computer Life Support
email: bertlandhope@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Computer Support And Services in Kingston Open 24 hours
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://bertlandh.github.io/ # the base hostname & protocol for your site
twitter_username: bertlandhope
github_username:  bertlandh
image: /img/DHA-profile-BHope-300x300.jpg
gh_sponsor: bertlandh

remote_theme: chrisrhymes/bulma-clean-theme
#theme: bulma-clean-theme
google_analytics: TX3BcBQVQZ5oP4d_ZCkte_D9QY4pxJ3weFCQhOUekuI
livereload: true
favicon: /favicon.png

# Pagination settings
paginate: 6
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: bertlandh

# Build settings
markdown: kramdown

#Syntax Highlighter
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - github-pages

sass:
  style: compressed

collections:
  stories:
    output: true
  products: 
    output: true
    layout: product
    show_sidebar: false

exclude: [node_modules, gulpfile.js, vendor]

footer_menu: footer_menu

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Bertland Hope"
      layout: post
      hero_image: /img/blog-hero.jpg
      show_sidebar: true
  -
    scope:
      path: ""
      type: "stories"
    values:
      author: "Bertland Hope"
      layout: post
      hero_image: /img/stories.jpg
  

# SEO
author: 
  twitter: bertlandhope
lang: en_GB
logo: /img/avatar.png
twitter:
  username: bertlandhope
  card: summary_large_image
facebook:
  publisher: https://www.facebook.com/bertlandh
  name: Bertland Hope
  links:
    - https://www.twitter.com/bertlandhope
    - https://www.facebook.com/bertlandh
    - https://github.com/bertlandh

feed:
  collections:
    - stories