# Site Settings
remote_theme: chrisrhymes/bulma-clean-theme
lang: en
title: Bertland Hope
tagline: Computer Life Support
email: bertlandhope@gmail.com
description: >
  Professional website
baseurl: "/"
url: "https://bertlandh.github.io"
permalink: pretty
#favicon: favicon.ico
#gh_sponsor: chrisrhymes
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top

paginate: 5
paginate_path: "/news/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: 


plugins:
  - github-pages
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

google_analytics: TX3BcBQVQZ5oP4d_ZCkte_D9QY4pxJ3weFCQhOUekuI

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Bertland Hope"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
